Wiki Updation #2
NilPointer-Software/bdfd-wiki pull request #147
Opened 2022-07-21 11:51 UTC by Priyanuj09

2022-07-21 15:12 UTC, MineBartekSA commented
Oh boy, 57 files.... this will take me a while to review

2022-07-21 19:50 UTC, ShiroNotFriday commented
> Oh boy, 57 files.... this will take me a while to review

Just in case, I prepared a coffin for you. 👌

2022-07-21 19:52 UTC, MineBartekSA requested changes
Thanks for taking your time to improve our wiki.
But there are a few changes I'd like you to make.
Also, please correct arguments in `$authorURL[]`

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/footerIcon.md
> +- `embedIndex` - What embed the footer icon should belong to. Default is `1`. [(learn more)](/src/resources/embedIndexes.md)
Please correct arguments
[JSON function data](https://botdesignerdiscord.com/public/api/function/$footerIcon[])

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/image.md
> +- `embedIndex` - What embed the image should belong to. Default is `1`. [(learn more)](/src/resources/embedIndexes.md)
Please correct arguments
[JSON function data](https://botdesignerdiscord.com/public/api/function/$image[])

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/lowestRoleWithPerms.md
> +- `permissions` - The permissions that the role needs to have.  [(see permissions list)](/src/resources/embedIndexes.md). Use `;` as separator for multiple permissions
Wrong link destination

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/onlyBotChannelPerms.md
> +- `permissions` - The [permissions](/src/resources/permissions.md) that the bot needs to execute the command. Separate permissions with `;`.
Please correct arguments in the full function
[JSON function data](https://botdesignerdiscord.com/public/api/function/$onlyBotChannelPerms[])

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/onlyBotPerms.md
> +- `permissions` - The [permissions](/src/resources/permissions.md) that the bot needs to run the command.
Please correct arguments in the full function
[JSON function data](https://botdesignerdiscord.com/public/api/function/$onlyBotPerms[])

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/removeSplitTextElement.md
>  Removes a certain element from the [$textSplit](https://nilpointer-software.github.io/bdfd-wiki/bdscript/textSplit.html) values.
Please correct the link destination to be relative

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/thumbnail.md
> +- `embedIndex` - What embed the thumbnail should belong to. Default is `1`. [(learn more)](../resources/embedIndexes.md)
Please correct arguments
[JSON function data](https://botdesignerdiscord.com/public/api/function/$thumbnail[])

2022-07-21 19:52 UTC, MineBartekSA commented on src/bdscript/title.md
> +- `embedIndex` - What embed the title should belong to. Default is `1`. [(learn more)](../resources/embedIndexes.md)
Please correct arguments (`text` can stay)
[JSON function data](https://botdesignerdiscord.com/public/api/function/$title[])

2022-07-22 08:38 UTC, MineBartekSA requested changes

2022-07-22 08:38 UTC, MineBartekSA commented on src/bdscript/editEmbedIn.md
> +- `color` - The embed border color, must be a valid [color hex](https://htmlcolorcodes.com/color-picker) or color integer number. Use `0` for default color.
The `color` argument **is** optional, so please add this information to its description

2022-07-22 08:38 UTC, MineBartekSA commented on src/bdscript/editEmbedIn.md
>  $editEmbedIn[time;title;description;footer;color]
Please add round brackets
[JSON function data](https://botdesignerdiscord.com/public/api/function/$editEmbedIn[])

2022-07-22 09:21 UTC, MineBartekSA approved these changes
Thanks for your hard work

2022-07-22 09:22 UTC, merged