Gateway Intents Guide
NilPointer-Software/bdfd-wiki pull request #151
Opened 2022-08-06 14:27 UTC by ShiroNotFriday

2022-08-06 14:33 UTC, ShiroNotFriday commented
Let me know if attachments don't work. Due to the current weak internet, I was not able to check their valid display on the page and so on.

2022-08-06 15:18 UTC, noituri commented
The embedded videos do not work

2022-08-06 16:07 UTC, MineBartekSA requested changes
Aside from fixing the videos, please add information about the `Message Content Intent`

2022-08-06 17:08 UTC, MineBartekSA commented on src/guides/gatewayIntents.md
> +This guide will tell you how to use Gateway Intents in BDFD, and what they are for.
`This guide will tell you` isn't wrong, but `This guide will explain to you` or `In this guide, you will learn` would be better.

2022-08-06 18:50 UTC, ShiroNotFriday commented
I will add attachments tomorrow. I'm out of city right now, so my poor internet connection doesn't allow me to add my attachments properly. I waited over an hour for them to upload to the resource, but... no need to explain.

2022-08-06 18:53 UTC, MineBartekSA reviewed
For now, looks good.
We'll wait for you to add the gifs

2022-08-07 13:59 UTC, MineBartekSA approved these changes
Thanks for your hard work

2022-08-07 13:59 UTC, merged