New themes
NilPointer-Software/bdfd-wiki pull request #207
Opened 2022-10-29 18:58 UTC by Rainb0wKey

2022-10-29 19:06 UTC, Rainb0wKey commented
Test

2022-10-29 19:41 UTC, Priyanuj-Gogoi requested changes
Hello Rainb0wKey,
Do update `book.js` and `index.hbs` too. Your PR is incomplete!

2022-10-29 19:50 UTC, Rainb0wKey commented
Ready!

2022-10-29 20:15 UTC, Priyanuj-Gogoi commented on src/theme/index.hbs
> +				<li role="none"><button role="menuitem" class="theme" id="ios">{{ theme_option "IOS theme" }}</button></li>
```suggestion
				<li role="none"><button role="menuitem" class="theme" id="ios">{{ theme_option "iOS" }}</button></li>
```

2022-10-29 20:56 UTC, noituri requested changes

2022-10-29 20:56 UTC, noituri commented on src/theme/index.hbs
> +				<li role="none"><button role="menuitem" class="theme" id="ios">{{ theme_option "iOS" }}</button></li>
Please indent the code
```suggestion
                                <li role="none"><button role="menuitem" class="theme" id="coal">{{ theme_option "Coal" }}</button></li>
                                <li role="none"><button role="menuitem" class="theme" id="navy">{{ theme_option "Navy" }}</button></li>
                                <li role="none"><button role="menuitem" class="theme" id="ayu">{{ theme_option "Ayu" }}</button></li>
                                <li role="none"><button role="menuitem" class="theme" id="green">{{ theme_option "Green" }}</button></li>
                                <li role="none"><button role="menuitem" class="theme" id="ios">{{ theme_option "iOS" }}</button></li>
```

2022-10-29 20:59 UTC, Priyanuj-Gogoi approved these changes
Thank you for contributing!

2022-10-29 21:13 UTC, Rainb0wKey commented
### Thanks!

2022-10-30 11:55 UTC, MineBartekSA approved these changes

2022-10-30 12:59 UTC, noituri approved these changes

2022-10-30 13:01 UTC, merged