Changing Information about Message Content Intent
NilPointer-Software/bdfd-wiki pull request #230
Opened 2022-11-01 19:40 UTC by NightNutSky

2022-11-02 02:27 UTC, Priyanuj-Gogoi requested changes
Hello NightNutSky,
If you can, please do update the GIF too and “How to enable Gateway Intents in BDFD App”. Previously, we have to manually select the intents in the app. As of now, "Intents" are automatically synced!

2022-11-02 06:23 UTC, Priyanuj-Gogoi requested changes
An explanation of about Presence Intent & Members Intent would also be good if you could explain a bit. Additionally, include `$getCustomStatus[]` function in Presence Intent function list and also, add a new line before a heading. For example:
```
### Presence Intent
Required ...

### Server Members Intent
Required ...

### Message Content Intent
Required ...
```

2022-11-02 06:23 UTC, Priyanuj-Gogoi commented on src/guides/gatewayIntents.md
> +
```suggestion
```

2022-11-02 07:39 UTC, MineBartekSA requested changes
Thank you, and please address @Priyanuj-Gogoi suggestions.

2022-11-02 07:39 UTC, MineBartekSA commented on src/guides/gatewayIntents.md
> +Required for the bot to receive information about the message (such as embed data).\
You can still receive the basic message information through the `MESSAGE_CREATE` gateway event, but you need this intent to receive the content data stored in the message.
```suggestion
Required for the bot to receive information stored in the message (such as message content or embed data).\
```

2022-11-02 15:57 UTC, Priyanuj-Gogoi requested changes
Hopefully, you can accept these changes. I have checked the Presence and Member Intent yet so far.

Also, i feel like we should add a short definition of "Gateway Intents" too and some more info about message content (like Affecting functions)

2022-11-02 15:57 UTC, priyanujgogoi-28 commented on src/guides/gatewayIntents.md
>  ## Use of Gateway Intents
```suggestion
## Privileged Gateway Intents
```

2022-11-02 15:57 UTC, priyanujgogoi-28 commented on src/guides/gatewayIntents.md
>  ## How to enable Gateway Intents
```suggestion
## Enabling Gateway Intents
```

2022-11-02 15:57 UTC, priyanujgogoi-28 commented on src/guides/gatewayIntents.md
> +Allows bot to get information about users in the guild (such as current status).
```suggestion
```

2022-11-02 15:57 UTC, priyanujgogoi-28 commented on src/guides/gatewayIntents.md
> +Required for the functions [`$membersCount[]`](../bdscript/membersCount.md#second-usage), [`$getUserStatus[]`](../bdscript/getUserStatus.md), and [`$getCustomStatus[]`](../bdscript/getCustomStatus.md
```suggestion
Allows the bot to receive `PRESENCE_UPDATE` event. This intent is primarily used to retrieve current user's presence state. For example, Activities (i.e PLAYING, LISTENING), Presence (i.e Online, Idle) and Custom status.

Functions which requires this intent are as follows:
- [`$getCustomStatus[]`](../bdscript/getCustomStatus.md)
- [`$getUserStatus[]`](../bdscript/getUserStatus.md)
- [`$membersCount[]`](../bdscript/membersCount.md#second-usage)
```

2022-11-02 15:57 UTC, Priyanuj-Gogoi commented on src/guides/gatewayIntents.md
> +Allows bot to get a list of users in the guild.
```suggestion
```

2022-11-02 15:57 UTC, Priyanuj-Gogoi commented on src/guides/gatewayIntents.md
> +Required for some callbacks to work (e.g. for [`$onJoined[]`](../callbacks/onJoined.md)).\
```suggestion
Allows the bot to receive `GUILD_MEMBER_ADD`, `GUILD_MEMBER_UPDATE, `GUILD_MEMBER_REMOVE`, and `THREAD_MEMBERS_UPDATE` events. This intent is primarily required to fetch entire list of guild members and getting specific guild member info (like guild joining, leaving, profile update etc.).

Callbacks which requires this intent are as follows:
- [`$onJoined[]`](../callbacks/onJoined.md)
- [`$onLeave[]`](../callbacks/onLeave.md)
```

2022-11-02 15:58 UTC, Priyanuj-Gogoi commented
I'll tty to check this a bit later for now.

2022-11-02 16:00 UTC, Priyanuj-Gogoi commented on src/guides/gatewayIntents.md
>  ## How to enable Gateway Intents
Shortening of Headers as stated in [CONTRIBUTING.md](https://github.com/NilPointer-Software/bdfd-wiki/blob/dev/CONTRIBUTING.md#shortening-headers) file

2022-11-03 19:36 UTC, Priyanuj-Gogoi approved these changes
Thanks!

2022-11-03 20:17 UTC, noituri requested changes
Thanks for contributing :)

2022-11-03 20:17 UTC, noituri commented on src/guides/gatewayIntents.md
> +Privileged Gateway Intents are special intents which needs to be manually enabled in your bot application settings.
```suggestion
Privileged Gateway Intents are special intents which need to be manually enabled in your bot application settings.
```

2022-11-03 22:43 UTC, noituri approved these changes

2022-11-04 07:25 UTC, MineBartekSA approved these changes

2022-11-04 07:25 UTC, merged