Favicon
NilPointer-Software/bdfd-wiki pull request #235
Opened 2022-11-12 21:08 UTC by NightNutSky

2022-11-12 21:22 UTC, Priyanuj-Gogoi requested changes

2022-11-12 21:22 UTC, Priyanuj-Gogoi commented on src/theme/index.hbs
> +        <link rel="icon" href="{{ path_to_root }}theme/favicon.png">
```suggestion
        <link rel="icon" href="{{ path_to_root }}favicon.png">
        <link rel="apple-touch-icon" href="{{ path_to_root }}favicon.png">

```

2022-11-12 21:30 UTC, Priyanuj-Gogoi approved these changes
Thanks you!

2022-11-13 09:56 UTC, noituri approved these changes

2022-11-13 09:56 UTC, merged