Patch 9
NilPointer-Software/bdfd-wiki pull request #238
Opened 2022-11-20 12:07 UTC by Rainb0wKey

Новые функции ( `$getChannelVar` | `$setChannelVar` | `$resetChannelVar` )

2022-11-20 12:26 UTC, Priyanuj-Gogoi requested changes
Checked only the three functions yet. Variables guides soon.

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +## Usage
```suggestion
## Syntax
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +$getChannelVar[variableName;(optional) channelID]
```suggestion
$getChannelVar[Name;(Channel ID)]
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +### Breakdown
```suggestion
### Parameters
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +- `variableName` - The name of the variable to get.
```suggestion
- `Name`: The name of the variable to get.
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +- `channelID` - The channel to get the value for. If no channelID is inputted, then the current channel is used.
```suggestion
- `Channel ID`: The channel to get the value for. If no channel ID is provided, then the current channel is used.
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/resetChannelVar.md
> +Resets a channel variable back to it's default value *(the one inputted in the app)* **for every server**.
```suggestion
Resets a channel variable back to it's default value *(the one provided in the app)* for every server.
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/resetChannelVar.md
> +> 🧙‍♂️ Use this function wisely!
```suggestion
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/resetChannelVar.md
> +
```suggestion
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/resetChannelVar.md
> +## Usage
```suggestion
## Syntax
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/resetChannelVar.md
> +$resetChannelVar[variableName]
```suggestion
$resetChannelVar[Name]
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/resetChannelVar.md
> +### Breakdown
```suggestion
### Parameters
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/resetChannelVar.md
> +- `variableName` - The name of the variable to reset.
```suggestion
- `Name`: The name of the variable to reset.
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +## Usage
```suggestion
## Syntax
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +$setUserVar[variableName;newValue;(channelID)]
```suggestion
$setChannelVar[Name;Value;(Channel ID)]
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +### Breakdown
```suggestion
### Parameters
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +- `variableName` - The variable to update.
```suggestion
- `Name`: The variable to update.
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +- `newValue` - The newly assigned variable value.
```suggestion
- `Value`: The newly assigned variable value.
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +- `channelID` - The channel to assign the new value to, uses current channel if no 'channelID' is provided.
```suggestion
- `Channel ID`: The channel to assign the new value to, uses current channel if no 'channel ID' is provided.
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +> 📝 Channel variables value has a max character limit of 499.
```suggestion
> 📌 Channel variables value has a max character limit of 499 (4999, if premium).
```

2022-11-20 12:26 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +[See more in the Variables guide...](https://nilpointer-software.github.io/bdfd-wiki/guides/variables.html)
```suggestion
[See more in the Variables guide...](../guides/variables.md)
```

2022-11-20 12:36 UTC, MineBartekSA requested changes
Thank you for your hard work

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/getChannelVar.md
> +## Usage
```suggestion
## Syntax
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/getChannelVar.md
> +$getChannelVar[variableName;(optional) channelID]
```suggestion
$getChannelVar[Variable Name;(Channel ID)]
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/getChannelVar.md
> +- `channelID` - The channel to get the value for. If no channelID is inputted, then the current channel is used.
```suggestion
### Parameters
- `Variable Name`: The name of the variable to get.
- `Channel ID`: The channel to get the value for. If no Channel ID is present, then the current channel will be used.
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/resetChannelVar.md
> +## Usage
```suggestion
## Syntax
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/resetChannelVar.md
> +$resetChannelVar[variableName]
```suggestion
$resetChannelVar[Variable Name]
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/resetChannelVar.md
> +- `variableName` - The name of the variable to reset.
```suggestion
### Parameters
- `Variable Name`: The name of the variable to reset.
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/setChannelVar.md
> +## Usage
```suggestion
## Syntax
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/setChannelVar.md
> +$setUserVar[variableName;newValue;(channelID)]
```suggestion
$setUserVar[Variable Name;New Value;(Channel ID)]
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/setChannelVar.md
> +- `channelID` - The channel to assign the new value to, uses current channel if no 'channelID' is provided.
```suggestion
### Parameters
- `Variable Name`: The variable to update.
- `New Value`: The new variable value.
- `Channel ID`: The channel to assign the new value to. If no 'Channel ID' is present, the current channel will be used.
```

2022-11-20 12:36 UTC, MineBartekSA commented on src/bdscript/resetChannelVar.md
> +Resets a channel variable back to it's default value *(the one inputted in the app)* **for every server**.
```suggestion
Resets a channel variable back to its default value *(the one provided in the app)* **for every channel in every server**.
```

2022-11-20 13:16 UTC, Priyanuj-Gogoi requested changes
Due to clone suggestions, some of them got outdated and made some differences. Here's a fix:

2022-11-20 13:16 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +$setUserVar[Variable Name;New Value;(Channel ID)]
```suggestion
$setChannelVar[Variable Name;New Value;(Channel ID)]
```

2022-11-20 13:16 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +- `Channel ID`: The channel to assign the new value to, uses current channel if no 'channel ID' is provided.
```suggestion
- `Channel ID`: The channel to assign the new value to. If no 'Channel ID' is present, the current channel will be used.
```

2022-11-20 13:16 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +- `Name`: The variable to update.
```suggestion
- `Variable Name`: The variable to update.
```

2022-11-20 13:16 UTC, Priyanuj-Gogoi commented on src/bdscript/setChannelVar.md
> +- `Value`: The newly assigned variable value.
```suggestion
- `New Value`: The new variable value.
```

2022-11-20 13:16 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +$getChannelVar[Name;(Channel ID)]
```suggestion
$getChannelVar[Variable Name;(Channel ID)]
```

2022-11-20 13:16 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +- `Name`: The name of the variable to get.
```suggestion
- `Variable Name`: The name of the variable to get.
```

2022-11-20 13:16 UTC, Priyanuj-Gogoi commented on src/bdscript/getChannelVar.md
> +- `Channel ID`: The channel to get the value for. If no channel ID is provided, then the current channel is used.
```suggestion
- `Channel ID`: The channel to get the value for. If no Channel ID is present, then the current channel will be used.
```

2022-11-20 18:54 UTC, Priyanuj-Gogoi reviewed
*I couldn't suggest changes on some lines, so here are extra changes, i would like you to make in `src/guides/variables.md`*

1. Added "channels"
    https://github.com/NilPointer-Software/bdfd-wiki/blob/26f551a905669fde8525a655b9ae2c88e66516e7/src/guides/variables.md?plain=1#L4
   ```diff
   - Data can be assigned to users, servers, and globally.
   + Data can be assigned to users, servers, channels and globally.
   ```

2. List style
   https://github.com/NilPointer-Software/bdfd-wiki/blob/26f551a905669fde8525a655b9ae2c88e66516e7/src/guides/variables.md?plain=1#L11-L30
    ```mkd
    ### Creating Variables 
    > 📌 Creating variables can only be done in the app.

    Here's how to create a variable, which you can get and modify later:

    1. Select the bot you want to add the new variable to.
    2. Go to "Variables" tab.

        ![ex2](https://i.ibb.co/ng3yJNn/Screenshot-20220717-132641.png)
    3. Then, click "+ New variable" button.

         ![ex3](https://i.ibb.co/Mc0nL0b/Screenshot-20220717-133047.png) 
    4. Give the variable a name and value. 
  
         ![ex4](https://user-images.githubusercontent.com/69215413/126413362-99e23e07-b01a-4ded-8be3-454837cb1ca5.png) 
    5. Finally, save the changes! 

        ![ex5](https://i.ibb.co/dbpJDmr/Screenshot-20220717-133424.png) 
    ```

3. List style & fixed numbering
     https://github.com/NilPointer-Software/bdfd-wiki/blob/26f551a905669fde8525a655b9ae2c88e66516e7/src/guides/variables.md?plain=1#L32-L51
     ```mkd
     ### Editing Variables
     Here's how you can modify an existing variable's name/default value:

     1. Select the bot you want to edit the variable for.
     2. Go to "Variables" tab.

         ![ex2](https://i.ibb.co/ng3yJNn/Screenshot-20220717-132641.png)
     3. Click the edit/pencil icon near the variable name that you want to edit.

         ![ex3](https://user-images.githubusercontent.com/69215413/126413529-b4f1fce6-a0fc-4962-b67c-94020d37a858.png)
     4. Provide a new variable name and/or value.

         ![ex4](https://user-images.githubusercontent.com/69215413/126413336-3a0c376c-fa30-435f-b5e4-74100ca0859a.png)
     5. Finally, save the changes!

         ![ex5](https://i.ibb.co/dbpJDmr/Screenshot-20220717-133424.png)
     ```
4. List style & fix numbering
    https://github.com/NilPointer-Software/bdfd-wiki/blob/26f551a905669fde8525a655b9ae2c88e66516e7/src/guides/variables.md?plain=1#L53-L70
   ```mkd
   ### Deleting Variables
   Here's how you can delete variables:

   1. Select the bot you want to delete the variable for.
   2. Go to "Variables" tab.

       ![ex2](https://i.ibb.co/ng3yJNn/Screenshot-20220717-132641.png)
   3. Select the variable you want to delete.

       ![ex3](https://user-images.githubusercontent.com/69215413/126413671-48dfae45-50e1-446a-843d-46513123a33c.png)
   4. Finally, confirm the deletion!

       ![ex4](https://user-images.githubusercontent.com/69215413/126413742-e9fef40c-01e8-4713-9e61-99d71c2d88f7.png)

   > 📌 Deleting variables might return error message in those commands which were using the deleted variables.
   ```

5. Paragraph change & Line break
    https://github.com/NilPointer-Software/bdfd-wiki/blob/26f551a905669fde8525a655b9ae2c88e66516e7/src/guides/variables.md?plain=1#L73
   ```mkd
   [`$setVar`](../bdscript/setVar.md)/[`$getVar`](../bdscript/getVar.md) are global variable functions, this means they apply to universally *(i.e they don't change per-server or per-user)*.\
   However, if you provide a user ID in the optional `User ID` parameter then it becomes a global-user variable.

   Global-user variables value stay with the user in every server. The usage of global-user variables looks like this:
   - `$setVar[Variable Name;New Value;User ID]`
   - `$getVar[Variable Name;User ID]`.
   ```
---
Hopefully, do make these changes and after that, i will tell you next what to do.

2022-11-21 10:12 UTC, MineBartekSA requested changes
Please address @Priyanuj-Gogoi current and upcoming concerns

2022-11-23 02:36 UTC, priyanujgogoi-28 requested changes

2022-11-23 02:36 UTC, priyanujgogoi-28 commented on src/guides/variables.md
> +Variables are how we store data in BDFD. Data can be assigned to users, servers, channels and globally. Each variable has two elements, which we will breakdown in this section.
```suggestion
Variables are how we store data in BDFD. Data can be assigned to users, servers, channels, and globally. Each variable has two elements, which we will breakdown in this section.
```

2022-11-23 02:36 UTC, priyanujgogoi-28 commented on src/guides/variables.md
> +- `$getVar[Variable Name;User ID]`.
```suggestion
[`$setVar`](../bdscript/setVar.md)/[`$getVar`](../bdscript/getVar.md) are global variable functions, this means they apply to universally *(i.e they don't change per-server, per-channel, or per-user)*.\
However, if you provide a user ID in the optional `User ID` parameter then it becomes a global-user variable.

Global-user variables value stay same with the user in every server. The usage of global-user variables looks like this:
- `$setVar[Variable Name;New Value;User ID]`
- `$getVar[Variable Name;User ID]`
```

2022-11-23 02:36 UTC, priyanujgogoi-28 commented on src/guides/variables.md
>  - `name` - The name of the variable. This can't be modified by the bot, its used to "call" the current variable.
```suggestion
- `Name`: The name of the variable. This can't be modified by the bot, its used to "call" the current variable.
```

2022-11-23 02:36 UTC, priyanujgogoi-28 commented on src/guides/variables.md
> +- `value` - The value of the variable. This can be modified by the bot, its returned when the variable name is called in `$getVar`/`$getUserVar`/`$getServerVar`/`$getChannelVar`.
```suggestion
- `Value`: The value of the variable. This can be modified by the bot, its returned when the variable name is called in `$getVar`/`$getUserVar`/`$getServerVar`/`$getChannelVar`.
```

2022-11-23 02:36 UTC, priyanujgogoi-28 commented on src/guides/variables.md
> + ### Creating Variables
```suggestion
### Creating Variables
```

2022-11-23 02:36 UTC, priyanujgogoi-28 commented on src/guides/variables.md
> +> 🧙‍♂️ The trigger for this command will be your bot's prefix, example: `!`.
```suggestion
- `$setChannelVar[Variable Name;New Value;(Channel ID)]`: Sets the provided variable to 'New Value' for the provided 'Channel ID', or the channel that the command was ran in; if no 'Channel ID' was provided.
- `$getChannelVar[Variable Name;(Channel ID)]`: Gets the current value for the provided channel variable. Returns the current channel's variable value if no 'Channel ID' is provided.

### Channel Variables - Examples
Here's the variable we're working with:

![ex](https://user-images.githubusercontent.com/113303649/202899818-b265e793-9a56-4a41-9539-9af01b622de8.png)

This command adds `1` uses to the 'Uses' variable value, everytime it is ran.

> 📌 The trigger for this command will be your bot's prefix, example: `!`.
```

2022-11-23 02:36 UTC, priyanujgogoi-28 commented on src/guides/variables.md
> + ### Deleting Variables
```suggestion
### Deleting Variables
```

2022-11-23 14:05 UTC, Priyanuj-Gogoi approved these changes
Thank you for considering my suggested changes. I have completed my review.

2022-11-23 15:45 UTC, Rainb0wKey commented
Ok

2022-11-24 11:40 UTC, MineBartekSA requested changes
Please make this last little change

2022-11-24 11:40 UTC, MineBartekSA commented on src/guides/variables.md
> +[`$setVar`](../bdscript/setVar.md)/[`$getVar`](../bdscript/getVar.md) are global variable functions, this means they apply to universally *(i.e they don't change per-server, per-channel, or per-user)
```suggestion
[`$setVar`](../bdscript/setVar.md)/[`$getVar`](../bdscript/getVar.md) are global variable functions, which means they apply universally *(i.e they don't change per-server, per-channel, or per-user)*.\
```

2022-11-25 13:56 UTC, MineBartekSA approved these changes
Thank you for your hard work!

2022-11-25 13:56 UTC, merged