Update 4
NilPointer-Software/bdfd-wiki pull request #251
Opened 2022-12-29 17:01 UTC by Rainb0wKey

All "A"

2022-12-29 18:42 UTC, Rainb0wKey commented
Tomorrow I plan to update all pages to "B"

2022-12-30 13:17 UTC, MineBartekSA requested changes

2022-12-30 13:17 UTC, MineBartekSA commented on src/bdscript/authorURL.md
> +- `index`: What embed the author url should belong to. (Optional) [(learn more)](../resources/embedIndexes.md)
```suggestion
- `index`: To which embed the author URL will be added. (Optional) [(learn more)](../resources/embedIndexes.md)
```

2022-12-30 13:17 UTC, MineBartekSA commented on src/bdscript/authorOfMessage.md
> +>  [How get message/channel ID guide.](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)
```suggestion
>  [How to get the message/channel ID guide.](https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)
```

2022-12-30 13:17 UTC, MineBartekSA commented on src/bdscript/authorOfMessage.md
> +- `message ID`: The message that the bot returns the author ID for.
```suggestion
- `channel ID`: The channel where the message was sent in.
- `message ID`: The message for which the author ID will be returned.
```

2022-12-30 13:17 UTC, MineBartekSA commented on src/bdscript/authorIcon.md
> +- `index`: What embed the author icon should belong to. _(Optional)_ [(learn more)](../resources/embedIndexes.md)
```suggestion
- `image url`: The image for the author icon. This must be a valid image URL.
- `index`: To which embed the author icon will be added. _(Optional)_ [(learn more)](../resources/embedIndexes.md)
```

2022-12-30 13:17 UTC, MineBartekSA commented on src/bdscript/author.md
> +- `index`: What embed the author text should belong to. _(Optional)_ [(learn more)](../resources/embedIndexes.md)
```suggestion
- `index`: To which embed the author text will be added. _(Optional)_ [(learn more)](../resources/embedIndexes.md)
```

2022-12-30 18:10 UTC, MineBartekSA approved these changes
Thank you for your contribution

2022-12-30 18:10 UTC, merged