Update 5
NilPointer-Software/bdfd-wiki pull request #252
Opened 2022-12-30 08:04 UTC by Rainb0wKey

YES

2022-12-30 13:43 UTC, MineBartekSA requested changes
I want you to redo the `ban` and `banID` pages.
I did some comments, but they are mostly just spelling mistakes and such.
I want you to highlight the simple functions in them too.

Because both `ban` and `banID` are Simple **and** Complex functions.
They work differently from each other, so they need to be better explained.
You can quickly look up their in-app descriptions here: [`$ban`](https://botdesignerdiscord.com/public/function/$ban), [`$ban[]`](https://botdesignerdiscord.com/public/function/$ban[]), [`$banID`](https://botdesignerdiscord.com/public/function/$banID), and [`$banID[]`](https://botdesignerdiscord.com/public/function/$banID[]).
(As a side note, we [the developers] need to make some of these in-app descriptions more verbose)

You also made some serious mistakes with arguments too.
The `reason` argument is always required but can be left empty in both functions.

2022-12-30 13:43 UTC, MineBartekSA commented on src/bdscript/blackListRolesIDs.md
> +- `error message`: The message that sends if the user has a role in the blacklist.
```suggestion
- `error message`: The message that will be sent if the user has a role from the blacklist.
```

2022-12-30 13:43 UTC, MineBartekSA commented on src/bdscript/blackListRoles.md
> +- `error message`: The message that appears when the user has a role in the blacklist.
```suggestion
- `error message`: The message that will be sent if the user has a role from the blacklist.
```

2022-12-30 13:43 UTC, MineBartekSA commented on src/bdscript/blackListIDs.md
> +- `error message`: The message that appears when the user running the command is blacklisted.
```suggestion
- `error message`: The message that will be sent when the user running the command is blacklisted.
```

2022-12-30 13:43 UTC, MineBartekSA commented on src/bdscript/banID.md
> +- `reason`: The reason for this action, which will be sent to the audit-log. _(Optional)_
```suggestion
- `reason`: The reason for this action, which will be saved in the audit log. Can be left empty.
```

2022-12-30 13:43 UTC, MineBartekSA commented on src/bdscript/banID.md
> +- `user ID`: Gets the user to ban. _(Optional)_
```suggestion
- `user ID`: The user to ban. _(Optional)_ Can be omitted, then the ID will be taken from the last part of the command message.
```

2022-12-30 13:43 UTC, MineBartekSA commented on src/bdscript/banID.md
> +$ban[(reason;user ID)]
```suggestion
$banID[reason;(user ID)]
```

2022-12-30 13:43 UTC, MineBartekSA commented on src/bdscript/ban.md
> +- `reason`: The reason for this action, which will be sent to the audit-log. _(Optional)_
```suggestion
- `reason`: The reason for this action, which will be save in the audit log. Can be left empty.
```

2022-12-30 13:50 UTC, Rainb0wKey commented
For all page changes. I only changed the description of the arguments 2 times. They were like this until my change.

2022-12-30 14:04 UTC, Rainb0wKey commented
My understanding is that I will need to create 2 more pages for these functions? with other arguments?

2022-12-30 20:05 UTC, MineBartekSA commented
The current design of the wiki doesn't allow for separate pages for simple and complex functions with the same name.
At least without renaming a whole lot of pages.
I was thinking of just keeping it how it is right now.

Pages are titled with the "base" name and they cover every function with that name like [`$dm`](https://nilpointer-software.github.io/bdfd-wiki/nightly/bdscript/dm.html) or the current [`$banID`](https://nilpointer-software.github.io/bdfd-wiki/nightly/bdscript/banID.html) does.
And since you are rewriting those pages, you could try to create a new and better way to address simple and complex functions on the same page.

I'd say that the current way pages like this are structured isn't that great.
They especially don't highlight that technically `$dm` and `$dm[]` are two different functions.
Sure, most people don't ever need to know about this, but it would hurt to make some sort of distinction between them.
Especially **if** they differ significantly in behaviour. Thankfully, most functions aren't like that.

I'm leaving it to you how you end up writing those pages.
The only thing I'd like you to not forget is that there are simple and complex functions with the same names.

2022-12-30 23:50 UTC, DevSpen commented
Although it doesn’t necessarily need to addressed in this pull request, I think we need to update SUMMARY.md and some wiki pages to represent functions the same way the app does. The more coherent the better.
- Functions without brackets would be shown as all functions are currently are (`$functionName`)
- Functions with brackets would be shown with brackets (`$functionName[]`)
- "Analogous function[s]"—functions w/ same name but one has brackets and the other doesn’t—would have separate pages regarding them.
    - There would be a note on each page linking to the other page on the respective function (i.e `$functionName`'s wiki would have a note saying there is another function `$functionName[]`)

@MineBartekSA On the developer end, how do you guys link a function within the app to its respective wiki page? As of right now, it doesn’t include brackets no matter if the function has brackets or not (which is how it should work based on the current design). Also, some functions (like the ones relating to buttons) only link to the Buttons guide within the wiki and not the specific function—is that pre-programmed behavior? Could things like that be changed smoothly though?

2022-12-31 10:48 UTC, MineBartekSA commented
To have an easier transition and to help people distinguish simple and complex functions, we could split the `BDScript` section in two, like so:

- BDScript
  - Simple functions
    - $message
  - Complex functions
    - $message[]

Then pages and URLs wouldn't need to include `[]` in them, which would probably help in some cases.

@DevSpen The app, as you'd expect, just trims the function name. And then there are explicitly chosen functions that open guides instead of their function wikis. To be honest, we probably should either add another button with `Open guide` for them.

Also, if we are going to reorganise the wiki in some way, we should probably move this discussion [somewhere else](https://github.com/NilPointer-Software/bdfd-wiki/discussions/254).

2023-01-04 21:04 UTC, MineBartekSA approved these changes
Thank you for your hard work

2023-01-04 21:04 UTC, merged