Update 11.2 + Update 16
NilPointer-Software/bdfd-wiki pull request #279
Opened 2023-01-27 20:40 UTC by Rainb0wKey

2023-01-30 10:51 UTC, MineBartekSA requested changes

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +## Used
If you could change this header in `buttons.md` too?
```suggestion
## Functions Used
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +## Supported Filters
```suggestion

## Supported Filters
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +## Syntax
```suggestion

## Syntax
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +- `channel ID` `(Type: Snowflake || Flag: Optional)`: The channel where the command will be awaited. Uses current channel, if `channel ID` is not given.
```suggestion

### Parameters
- `command name` `(Type: String || Flag: Required)`: The name used inside [`$awaitedCommand[]`](#awaitedcommand) and [`$awaitedCommandError[]`](#awaitedcommanderror) callbacks.
- `user ID` `(Type: Snowflake || Flag: Vacantable)`: The user the awaited command will trigger for. Uses command author, if `user ID` is not given.
- `channel ID` `(Type: Snowflake || Flag: Optional)`: The channel where the command will be awaited. Uses current channel, if `channel ID` is not given.

```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +_Triggered when an awaited command gets initiated._
This callback only runs after `$awaitFunc[]` was run and the given user sent a message in the given channel aka responded. So calling this initiation is not correct.
```suggestion

# $awaitedCommand
_Triggered when an awaited command gets responded to._
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +`$awaitedCommand[]` is a callback, which means it's used in the command trigger (not the code). The command is ran when an awaited command gets initiated.
```suggestion
`$awaitedCommand[]` is a callback, which means it's used in the command trigger (not the code). The command is only run when an awaited command gets responded to.

```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +- `filter`: It is used to limit user input. [Supported Filters](#supported-filters)
```suggestion

### Parameters
- `name`: The name used in [`$awaitFunc[]`](#awaitfunc) function.
- `filter`: Used to limit user input. [Supported Filters](#supported-filters)

```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +`$awaitedCommandError[]` is a callback, which means it's used in the command trigger (not the code). The command is ran when an awaited command doesn't match with provided filter.
```suggestion
`$awaitedCommandError[]` is a callback, which means it's used in the command trigger (not the code). The command is only run when an awaited command doesn't match with provided filter.
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +# Create Await
```suggestion
# Creating an awaited command
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +[**Used**](#used) > [**Supported Filters**](#supported-filters) > [**$awaitFunc[]**](#awaitfunc) > [**$awaitedCommand[]**](#awaitedcommand) > [**$awaitedCommandError[]**](#awaitedcommanderror) > [**C
```suggestion
[**Used**](#used) > [**Supported Filters**](#supported-filters) > [**$awaitFunc[]**](#awaitfunc) > [**$awaitedCommand[]**](#awaitedcommand) > [**$awaitedCommandError[]**](#awaitedcommanderror) > [**Creating an awaited command**](#creating-an-awaited-command)
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +2. Paste the following code: Code for the command with the `!say` trigger:
```suggestion

1. Create two commands with `!say` and `$awaitedCommand[say;]` triggers.
2. Paste the following code:

Code for the `!say` command:
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +Code for the command with the `$awaitedCommand[say;]` trigger:
```suggestion

Code for the command with the `$awaitedCommand[say;]` trigger:
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +3. Execute command `!say`
```suggestion

3. Execute command `!say`
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +2. Paste the following code: Code for the command with the `!odd` trigger:
```suggestion

1. Create two commands with `!odd` and `$awaitedCommand[odd;<yes/no/cancel>]` triggers.
2. Paste the following code:

Code for the `!odd` command:
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +Code for the command with the `$awaitedCommand[say;]` trigger:
```suggestion

Code for the command with the `$awaitedCommand[say;]` trigger:
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +3. Execute command `!odd`
```suggestion

3. Execute command `!odd`
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +2. Paste the following code: Code for the command with the `!number` trigger:
```suggestion

1. Create two commands with `!number` and `$awaitedCommand[number;<numeric>]` triggers.
2. Paste the following code:

Code for the `!number` command:
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +Code for the command with the `$awaitedCommand[number;<numeric>]` trigger:
```suggestion

Code for the command with the `$awaitedCommand[number;<numeric>]` trigger:
```

2023-01-30 10:51 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +3. Execute command `!number`
```suggestion

3. Execute command `!number`
```

2023-01-30 20:01 UTC, MineBartekSA requested changes
Change the `## Used` header to `## Functions Used` in `buttons.md`

2023-01-30 20:26 UTC, Rainb0wKey commented
ok

2023-01-30 20:46 UTC, MineBartekSA requested changes
I forgot about this

2023-01-30 20:46 UTC, MineBartekSA commented on src/guides/awaitedCommands.md
> +[**Used**](#used) > [**Supported Filters**](#supported-filters) > [**$awaitFunc[]**](#awaitfunc) > [**$awaitedCommand[]**](#awaitedcommand) > [**$awaitedCommandError[]**](#awaitedcommanderror) > [**C
```suggestion
[**Functions Used**](#functions-used) > [**Supported Filters**](#supported-filters) > [**$awaitFunc[]**](#awaitfunc) > [**$awaitedCommand[]**](#awaitedcommand) > [**$awaitedCommandError[]**](#awaitedcommanderror) > [**Creating an awaited command**](#creating-an-awaited-command)
```

2023-01-31 15:02 UTC, MineBartekSA approved these changes
Thank you for your hard work

2023-01-31 19:19 UTC, MineBartekSA commented
@Rainb0wKey please handle merge conflict

2023-02-06 20:11 UTC, Rainb0wKey commented
ok

2023-02-15 12:31 UTC, MineBartekSA approved these changes

2023-02-15 12:31 UTC, merged