Update 18
NilPointer-Software/bdfd-wiki pull request #294
Opened 2023-03-18 06:37 UTC by Rainb0wKey

Hello!

2023-03-27 08:33 UTC, noituri requested changes

2023-03-27 08:33 UTC, noituri commented on src/bdscript/customID.md
> +Can only be used with the [`$onInteraction`](/src/callbacks/onInteractionComplex.md) callback. Returns the custom ID of this interaction.
Please use relative url instead

```suggestion
Can only be used with the [`$onInteraction`](../callbacks/onInteractionComplex.md) callback. Returns the custom ID of this interaction.
```

2023-03-27 08:33 UTC, noituri commented on src/bdscript/date.md
> +> You can use [`$time[]`](/src/bdscript/time.md) to change the timezone.
```suggestion
> You can use [`$time[]`](./time.md) to change the timezone.
```

2023-03-27 17:05 UTC, Rainb0wKey commented
Thanks

2023-03-30 09:52 UTC, MineBartekSA approved these changes
Thank you for your contribution

2023-03-30 18:39 UTC, noituri approved these changes

2023-03-30 18:40 UTC, merged