Wiki Update 3
NilPointer-Software/bdfd-wiki pull request #315
Opened 2023-05-30 14:46 UTC by xNickyDev

Files from h-i
- Changed headers "Usage" to "Syntax"
- Added missing examples
- Split [`$hostingExpireTime`](https://github.com/NilPointer-Software/bdfd-wiki/blob/dev/src/bdscript/hostingExpireTime.md) into two files -> [`$hostingExpireTime[]`](https://github.com/NilPointer-Software/bdfd-wiki/blob/dev/src/bdscript/hostingExpireTimeComplex.md)
- Other small changes

2023-06-23 16:26 UTC, MineBartekSA commented
Sorry for the wait, I'll review this asap in the coming days

2023-06-26 07:35 UTC, Rainb0wKey commented
`$hostingExpireTime[Return unix timestamp]` > `$hostingExpireTime[Return unix timestamp?]`

2023-07-03 11:32 UTC, MineBartekSA requested changes

2023-07-03 11:32 UTC, MineBartekSA commented on src/bdscript/hostingExpireTime.md
> +Returns expire time for the hosting.
``` suggestion
Returns your bot's hosting expiration date.
```

2023-07-03 11:32 UTC, MineBartekSA commented on src/bdscript/hostingExpireTimeComplex.md
> +Returns expire time for the hosting. If "yes" is provided, the function returns the expire time in UNIX Timestamp.
``` suggestion
Returns your bot's hosting expiration date. If "yes" is provided, the function returns the expiration date in a UNIX timestamp.
```

2023-07-03 11:32 UTC, MineBartekSA commented on src/bdscript/hostingExpireTimeComplex.md
> +- `Return unix timestamp?` `(Type: Bool || Flag: Required)`: Whether to return the expiration time in UNIX Timestamp or not.
``` suggestion
- `Return unix timestamp?` `(Type: Bool || Flag: Required)`: Whether to return the expiration date in a UNIX timestamp or not.
```

2023-07-03 19:27 UTC, MineBartekSA approved these changes
Thank you for your hard work!

2023-07-03 19:30 UTC, merged