Update 19
NilPointer-Software/bdfd-wiki pull request #319
Opened 2023-06-26 07:28 UTC by Rainb0wKey

Soon part 2 of update (`$endif`/`$eleif[]`/Update of guide)

2023-06-26 12:36 UTC, caramellya-mei commented
Aren't categorized functions supposed to be kept to [general guides](https://github.com/nilpointer-software/bdfd-wiki/tree/dev/src/guides/general) now?
If you made it so the users don't get thrown into 404 page by opening `$if[]` from the app, make a redirect to [ifStatements.md](https://github.com/NilPointer-Software/bdfd-wiki/blob/dev/src/guides/general/ifStatements.md) in book.toml instead

2023-06-26 12:44 UTC, Rainb0wKey commented
I add all the functions from the guides to the functions section, in the guides you can find out how to use them, and on the pages you can find information about the function

2023-06-26 12:45 UTC, Rainb0wKey commented
`Awaited Commands` have already been moved to the Functions category

2023-07-03 10:55 UTC, MineBartekSA requested changes

2023-07-03 10:55 UTC, MineBartekSA commented on src/bdscript/if.md
> +Returns `true` if provided condition is true, otherwise `false` is returned.
```suggestion
Executes the following block of code if the provided condition is true.
```

2023-07-03 19:22 UTC, MineBartekSA approved these changes
Thank you for your hard work!

2023-07-03 19:22 UTC, merged