Update 23
NilPointer-Software/bdfd-wiki pull request #331
Opened 2023-07-06 16:52 UTC by Rainb0wKey

Updated guide (1/4)

2023-07-06 16:56 UTC, Rainb0wKey commented
I think this is a more understandable use case for BDFD, if you want, I can add examples

2023-07-10 10:11 UTC, MineBartekSA requested changes

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +In this guide you will learn how to create your own bot with BDFD.
``` suggestion
In this guide, you will learn how to create your own bot using BDFD.
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
>  - Then, press the *"Add Bot"* button to create a discord bot.
Discord now automatically creates a bot user

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +- Press the *"Edit invite link permissions"* button and choose the permissions that the bot will have when joined the server.
``` suggestion
- Press the *"Edit invite link permissions"* button and choose the permissions that the bot will have when joining a server.
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +- Then, click on the *"Add your bot to your server"* and selected the server.
``` suggestion
- Then, click on *"Add your bot to your server"* and selected the server.
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +- Click on the *"Continue"* button and your bot will be added to the server.
``` suggestion
- Click on *the "Continue"* button and your bot will be added to the selected server.
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +To create the first command, you must click on *"Commands"* in the selected bot and press on the *"+ Command creator"*.
``` suggestion
To create the first command, you must click on the *"Commands"* tab after selecting your bot and press on the *"+ Command creator"*.
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +- Click on *"Dashboard"* in the selected bot and press on the *"+ Add free hosting time"* button.
``` suggestion
- Click on the *"Dashboard"* tab after selecting your bot and press on the *"+ Add free hosting time"* button.
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +- Press on *"Dashboard"* button in the selected bot and click on *"+ Watch ad for 90 minutes of free hosting time"*.
``` suggestion
- Press on *"Dashboard"* tab after selecting your bot and click on *"+ Watch ad for 140 minutes of free hosting time"*.
- After watching the ad, your bot will receive 140 minutes of hosting time.
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +> If the bot is not online after these methods, then take a look at this page. [Why my bot is offline?](../../resources/troubleshooting.md#the-bot-is-offline)
``` suggestion
- Use [premium](../../premium/introduction.md#purchasing-premium-points) points to get hosting time without watching ads.
> If the bot is not online after these methods, then take a look at this page: [Why my bot is offline?](../../resources/troubleshooting.md#the-bot-is-offline)
```

2023-07-10 10:11 UTC, MineBartekSA commented on src/guides/introduction/beginning.md
> +Send a `!ping` command to the channel of the server you invited the bot to.
``` suggestion
Send a `!ping` command in a channel of the server you invited your bot to.
```

2023-07-11 09:14 UTC, MineBartekSA approved these changes
Thank you for your hard work!

2023-07-11 09:14 UTC, merged